/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksTodayRouteImport } from './routes/_tasks/today'
import { Route as TasksLaterRouteImport } from './routes/_tasks/later'
import { Route as TasksBacklogRouteImport } from './routes/_tasks/backlog'
import { Route as NotesStarredRouteImport } from './routes/_notes/starred'
import { Route as NotesInboxRouteImport } from './routes/_notes/inbox'
import { Route as TasksTodayIndexRouteImport } from './routes/_tasks/today.index'
import { Route as TasksLaterIndexRouteImport } from './routes/_tasks/later.index'
import { Route as TasksBacklogIndexRouteImport } from './routes/_tasks/backlog.index'
import { Route as NotesStarredIndexRouteImport } from './routes/_notes/starred.index'
import { Route as NotesInboxIndexRouteImport } from './routes/_notes/inbox.index'
import { Route as TasksTodayTaskIdRouteImport } from './routes/_tasks/today.$taskId'
import { Route as TasksLaterTaskIdRouteImport } from './routes/_tasks/later.$taskId'
import { Route as TasksBacklogTaskIdRouteImport } from './routes/_tasks/backlog.$taskId'
import { Route as NotesStarredNoteIdRouteImport } from './routes/_notes/starred.$noteId'
import { Route as NotesProjectsProjectIdRouteImport } from './routes/_notes/projects.$projectId'
import { Route as NotesInboxNoteIdRouteImport } from './routes/_notes/inbox.$noteId'
import { Route as NotesProjectsProjectIdIndexRouteImport } from './routes/_notes/projects.$projectId.index'
import { Route as NotesProjectsProjectIdNoteIdRouteImport } from './routes/_notes/projects.$projectId.$noteId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTodayRoute = TasksTodayRouteImport.update({
  id: '/_tasks/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksLaterRoute = TasksLaterRouteImport.update({
  id: '/_tasks/later',
  path: '/later',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksBacklogRoute = TasksBacklogRouteImport.update({
  id: '/_tasks/backlog',
  path: '/backlog',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesStarredRoute = NotesStarredRouteImport.update({
  id: '/_notes/starred',
  path: '/starred',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesInboxRoute = NotesInboxRouteImport.update({
  id: '/_notes/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTodayIndexRoute = TasksTodayIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TasksTodayRoute,
} as any)
const TasksLaterIndexRoute = TasksLaterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TasksLaterRoute,
} as any)
const TasksBacklogIndexRoute = TasksBacklogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TasksBacklogRoute,
} as any)
const NotesStarredIndexRoute = NotesStarredIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NotesStarredRoute,
} as any)
const NotesInboxIndexRoute = NotesInboxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NotesInboxRoute,
} as any)
const TasksTodayTaskIdRoute = TasksTodayTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => TasksTodayRoute,
} as any)
const TasksLaterTaskIdRoute = TasksLaterTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => TasksLaterRoute,
} as any)
const TasksBacklogTaskIdRoute = TasksBacklogTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => TasksBacklogRoute,
} as any)
const NotesStarredNoteIdRoute = NotesStarredNoteIdRouteImport.update({
  id: '/$noteId',
  path: '/$noteId',
  getParentRoute: () => NotesStarredRoute,
} as any)
const NotesProjectsProjectIdRoute = NotesProjectsProjectIdRouteImport.update({
  id: '/_notes/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesInboxNoteIdRoute = NotesInboxNoteIdRouteImport.update({
  id: '/$noteId',
  path: '/$noteId',
  getParentRoute: () => NotesInboxRoute,
} as any)
const NotesProjectsProjectIdIndexRoute =
  NotesProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => NotesProjectsProjectIdRoute,
  } as any)
const NotesProjectsProjectIdNoteIdRoute =
  NotesProjectsProjectIdNoteIdRouteImport.update({
    id: '/$noteId',
    path: '/$noteId',
    getParentRoute: () => NotesProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inbox': typeof NotesInboxRouteWithChildren
  '/starred': typeof NotesStarredRouteWithChildren
  '/backlog': typeof TasksBacklogRouteWithChildren
  '/later': typeof TasksLaterRouteWithChildren
  '/today': typeof TasksTodayRouteWithChildren
  '/inbox/$noteId': typeof NotesInboxNoteIdRoute
  '/projects/$projectId': typeof NotesProjectsProjectIdRouteWithChildren
  '/starred/$noteId': typeof NotesStarredNoteIdRoute
  '/backlog/$taskId': typeof TasksBacklogTaskIdRoute
  '/later/$taskId': typeof TasksLaterTaskIdRoute
  '/today/$taskId': typeof TasksTodayTaskIdRoute
  '/inbox/': typeof NotesInboxIndexRoute
  '/starred/': typeof NotesStarredIndexRoute
  '/backlog/': typeof TasksBacklogIndexRoute
  '/later/': typeof TasksLaterIndexRoute
  '/today/': typeof TasksTodayIndexRoute
  '/projects/$projectId/$noteId': typeof NotesProjectsProjectIdNoteIdRoute
  '/projects/$projectId/': typeof NotesProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inbox/$noteId': typeof NotesInboxNoteIdRoute
  '/starred/$noteId': typeof NotesStarredNoteIdRoute
  '/backlog/$taskId': typeof TasksBacklogTaskIdRoute
  '/later/$taskId': typeof TasksLaterTaskIdRoute
  '/today/$taskId': typeof TasksTodayTaskIdRoute
  '/inbox': typeof NotesInboxIndexRoute
  '/starred': typeof NotesStarredIndexRoute
  '/backlog': typeof TasksBacklogIndexRoute
  '/later': typeof TasksLaterIndexRoute
  '/today': typeof TasksTodayIndexRoute
  '/projects/$projectId/$noteId': typeof NotesProjectsProjectIdNoteIdRoute
  '/projects/$projectId': typeof NotesProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_notes/inbox': typeof NotesInboxRouteWithChildren
  '/_notes/starred': typeof NotesStarredRouteWithChildren
  '/_tasks/backlog': typeof TasksBacklogRouteWithChildren
  '/_tasks/later': typeof TasksLaterRouteWithChildren
  '/_tasks/today': typeof TasksTodayRouteWithChildren
  '/_notes/inbox/$noteId': typeof NotesInboxNoteIdRoute
  '/_notes/projects/$projectId': typeof NotesProjectsProjectIdRouteWithChildren
  '/_notes/starred/$noteId': typeof NotesStarredNoteIdRoute
  '/_tasks/backlog/$taskId': typeof TasksBacklogTaskIdRoute
  '/_tasks/later/$taskId': typeof TasksLaterTaskIdRoute
  '/_tasks/today/$taskId': typeof TasksTodayTaskIdRoute
  '/_notes/inbox/': typeof NotesInboxIndexRoute
  '/_notes/starred/': typeof NotesStarredIndexRoute
  '/_tasks/backlog/': typeof TasksBacklogIndexRoute
  '/_tasks/later/': typeof TasksLaterIndexRoute
  '/_tasks/today/': typeof TasksTodayIndexRoute
  '/_notes/projects/$projectId/$noteId': typeof NotesProjectsProjectIdNoteIdRoute
  '/_notes/projects/$projectId/': typeof NotesProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inbox'
    | '/starred'
    | '/backlog'
    | '/later'
    | '/today'
    | '/inbox/$noteId'
    | '/projects/$projectId'
    | '/starred/$noteId'
    | '/backlog/$taskId'
    | '/later/$taskId'
    | '/today/$taskId'
    | '/inbox/'
    | '/starred/'
    | '/backlog/'
    | '/later/'
    | '/today/'
    | '/projects/$projectId/$noteId'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inbox/$noteId'
    | '/starred/$noteId'
    | '/backlog/$taskId'
    | '/later/$taskId'
    | '/today/$taskId'
    | '/inbox'
    | '/starred'
    | '/backlog'
    | '/later'
    | '/today'
    | '/projects/$projectId/$noteId'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_notes/inbox'
    | '/_notes/starred'
    | '/_tasks/backlog'
    | '/_tasks/later'
    | '/_tasks/today'
    | '/_notes/inbox/$noteId'
    | '/_notes/projects/$projectId'
    | '/_notes/starred/$noteId'
    | '/_tasks/backlog/$taskId'
    | '/_tasks/later/$taskId'
    | '/_tasks/today/$taskId'
    | '/_notes/inbox/'
    | '/_notes/starred/'
    | '/_tasks/backlog/'
    | '/_tasks/later/'
    | '/_tasks/today/'
    | '/_notes/projects/$projectId/$noteId'
    | '/_notes/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotesInboxRoute: typeof NotesInboxRouteWithChildren
  NotesStarredRoute: typeof NotesStarredRouteWithChildren
  TasksBacklogRoute: typeof TasksBacklogRouteWithChildren
  TasksLaterRoute: typeof TasksLaterRouteWithChildren
  TasksTodayRoute: typeof TasksTodayRouteWithChildren
  NotesProjectsProjectIdRoute: typeof NotesProjectsProjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tasks/today': {
      id: '/_tasks/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TasksTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tasks/later': {
      id: '/_tasks/later'
      path: '/later'
      fullPath: '/later'
      preLoaderRoute: typeof TasksLaterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tasks/backlog': {
      id: '/_tasks/backlog'
      path: '/backlog'
      fullPath: '/backlog'
      preLoaderRoute: typeof TasksBacklogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_notes/starred': {
      id: '/_notes/starred'
      path: '/starred'
      fullPath: '/starred'
      preLoaderRoute: typeof NotesStarredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_notes/inbox': {
      id: '/_notes/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof NotesInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tasks/today/': {
      id: '/_tasks/today/'
      path: '/'
      fullPath: '/today/'
      preLoaderRoute: typeof TasksTodayIndexRouteImport
      parentRoute: typeof TasksTodayRoute
    }
    '/_tasks/later/': {
      id: '/_tasks/later/'
      path: '/'
      fullPath: '/later/'
      preLoaderRoute: typeof TasksLaterIndexRouteImport
      parentRoute: typeof TasksLaterRoute
    }
    '/_tasks/backlog/': {
      id: '/_tasks/backlog/'
      path: '/'
      fullPath: '/backlog/'
      preLoaderRoute: typeof TasksBacklogIndexRouteImport
      parentRoute: typeof TasksBacklogRoute
    }
    '/_notes/starred/': {
      id: '/_notes/starred/'
      path: '/'
      fullPath: '/starred/'
      preLoaderRoute: typeof NotesStarredIndexRouteImport
      parentRoute: typeof NotesStarredRoute
    }
    '/_notes/inbox/': {
      id: '/_notes/inbox/'
      path: '/'
      fullPath: '/inbox/'
      preLoaderRoute: typeof NotesInboxIndexRouteImport
      parentRoute: typeof NotesInboxRoute
    }
    '/_tasks/today/$taskId': {
      id: '/_tasks/today/$taskId'
      path: '/$taskId'
      fullPath: '/today/$taskId'
      preLoaderRoute: typeof TasksTodayTaskIdRouteImport
      parentRoute: typeof TasksTodayRoute
    }
    '/_tasks/later/$taskId': {
      id: '/_tasks/later/$taskId'
      path: '/$taskId'
      fullPath: '/later/$taskId'
      preLoaderRoute: typeof TasksLaterTaskIdRouteImport
      parentRoute: typeof TasksLaterRoute
    }
    '/_tasks/backlog/$taskId': {
      id: '/_tasks/backlog/$taskId'
      path: '/$taskId'
      fullPath: '/backlog/$taskId'
      preLoaderRoute: typeof TasksBacklogTaskIdRouteImport
      parentRoute: typeof TasksBacklogRoute
    }
    '/_notes/starred/$noteId': {
      id: '/_notes/starred/$noteId'
      path: '/$noteId'
      fullPath: '/starred/$noteId'
      preLoaderRoute: typeof NotesStarredNoteIdRouteImport
      parentRoute: typeof NotesStarredRoute
    }
    '/_notes/projects/$projectId': {
      id: '/_notes/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof NotesProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_notes/inbox/$noteId': {
      id: '/_notes/inbox/$noteId'
      path: '/$noteId'
      fullPath: '/inbox/$noteId'
      preLoaderRoute: typeof NotesInboxNoteIdRouteImport
      parentRoute: typeof NotesInboxRoute
    }
    '/_notes/projects/$projectId/': {
      id: '/_notes/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof NotesProjectsProjectIdIndexRouteImport
      parentRoute: typeof NotesProjectsProjectIdRoute
    }
    '/_notes/projects/$projectId/$noteId': {
      id: '/_notes/projects/$projectId/$noteId'
      path: '/$noteId'
      fullPath: '/projects/$projectId/$noteId'
      preLoaderRoute: typeof NotesProjectsProjectIdNoteIdRouteImport
      parentRoute: typeof NotesProjectsProjectIdRoute
    }
  }
}

interface NotesInboxRouteChildren {
  NotesInboxNoteIdRoute: typeof NotesInboxNoteIdRoute
  NotesInboxIndexRoute: typeof NotesInboxIndexRoute
}

const NotesInboxRouteChildren: NotesInboxRouteChildren = {
  NotesInboxNoteIdRoute: NotesInboxNoteIdRoute,
  NotesInboxIndexRoute: NotesInboxIndexRoute,
}

const NotesInboxRouteWithChildren = NotesInboxRoute._addFileChildren(
  NotesInboxRouteChildren,
)

interface NotesStarredRouteChildren {
  NotesStarredNoteIdRoute: typeof NotesStarredNoteIdRoute
  NotesStarredIndexRoute: typeof NotesStarredIndexRoute
}

const NotesStarredRouteChildren: NotesStarredRouteChildren = {
  NotesStarredNoteIdRoute: NotesStarredNoteIdRoute,
  NotesStarredIndexRoute: NotesStarredIndexRoute,
}

const NotesStarredRouteWithChildren = NotesStarredRoute._addFileChildren(
  NotesStarredRouteChildren,
)

interface TasksBacklogRouteChildren {
  TasksBacklogTaskIdRoute: typeof TasksBacklogTaskIdRoute
  TasksBacklogIndexRoute: typeof TasksBacklogIndexRoute
}

const TasksBacklogRouteChildren: TasksBacklogRouteChildren = {
  TasksBacklogTaskIdRoute: TasksBacklogTaskIdRoute,
  TasksBacklogIndexRoute: TasksBacklogIndexRoute,
}

const TasksBacklogRouteWithChildren = TasksBacklogRoute._addFileChildren(
  TasksBacklogRouteChildren,
)

interface TasksLaterRouteChildren {
  TasksLaterTaskIdRoute: typeof TasksLaterTaskIdRoute
  TasksLaterIndexRoute: typeof TasksLaterIndexRoute
}

const TasksLaterRouteChildren: TasksLaterRouteChildren = {
  TasksLaterTaskIdRoute: TasksLaterTaskIdRoute,
  TasksLaterIndexRoute: TasksLaterIndexRoute,
}

const TasksLaterRouteWithChildren = TasksLaterRoute._addFileChildren(
  TasksLaterRouteChildren,
)

interface TasksTodayRouteChildren {
  TasksTodayTaskIdRoute: typeof TasksTodayTaskIdRoute
  TasksTodayIndexRoute: typeof TasksTodayIndexRoute
}

const TasksTodayRouteChildren: TasksTodayRouteChildren = {
  TasksTodayTaskIdRoute: TasksTodayTaskIdRoute,
  TasksTodayIndexRoute: TasksTodayIndexRoute,
}

const TasksTodayRouteWithChildren = TasksTodayRoute._addFileChildren(
  TasksTodayRouteChildren,
)

interface NotesProjectsProjectIdRouteChildren {
  NotesProjectsProjectIdNoteIdRoute: typeof NotesProjectsProjectIdNoteIdRoute
  NotesProjectsProjectIdIndexRoute: typeof NotesProjectsProjectIdIndexRoute
}

const NotesProjectsProjectIdRouteChildren: NotesProjectsProjectIdRouteChildren =
  {
    NotesProjectsProjectIdNoteIdRoute: NotesProjectsProjectIdNoteIdRoute,
    NotesProjectsProjectIdIndexRoute: NotesProjectsProjectIdIndexRoute,
  }

const NotesProjectsProjectIdRouteWithChildren =
  NotesProjectsProjectIdRoute._addFileChildren(
    NotesProjectsProjectIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotesInboxRoute: NotesInboxRouteWithChildren,
  NotesStarredRoute: NotesStarredRouteWithChildren,
  TasksBacklogRoute: TasksBacklogRouteWithChildren,
  TasksLaterRoute: TasksLaterRouteWithChildren,
  TasksTodayRoute: TasksTodayRouteWithChildren,
  NotesProjectsProjectIdRoute: NotesProjectsProjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
